accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signin/', SignupView.as_view(), name='signin'),
]

mitmproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mitmlearning.urls')),
    path('accounts/',include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.forms.widgets import PasswordInput, TextInput

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ユーザ名'})
            self.fields['username'].label = False
            self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'パスワード'}) 
            self.fields['password'].label = False

accounts/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from  .forms import LoginForm
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import SignupForm


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('index')

class Login(LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm

#ログアウト機能の処理
class Logout(LogoutView):
    template_name = 'logout.html'

accounts/templates/accounts/signup.html
{% extends 'base2.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}

{% block navbar %}
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'scenario' %}">学習シナリオ</a></li>
            <li><a href="{% url 'feedback' %}">フィードバック</a></li>
            <li><a class="current" href="{% url 'list-term' %}">用語集</a></li>
            {% if request.user.is_anonymous %}
            <li><a href="{% url 'accounts:signin' %}">サインイン</a></li>
            <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
            {% else %}
            <li><a href="/"><span>{{ request.user }}さん</span></a></li>
            {% endif %}
            <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
<div class="card my-4">
    <h4 class="midashi">ログイン</h4>
    <div class="card-body">
        <div class="row">
            <div>アカウントを作成します。</div>
            <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
              {% csrf_token %}
              <input type="text" name="username" class="form-control mt-4" placeholder="ユーザー ID">
              <input type="password" name="password1" class="form-control mt-4" placeholder="パスワード">
              <input type="password" name="password2" class="form-control mt-4" placeholder="パスワード確認用">
              {% if form.errors %}
                <span class="mb-2 small text-danger d-block text-start">利用できないユーザー ID やパスワードの可能性があります。入力内容を再度ご確認ください。</span>
              {% endif %}
              <button type="submit" class="btn btn-success m-2">アカウント作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}